name: PHPUnit Tests

on:
  push:
    branches: [ master, main, tests ]
  pull_request:
    branches: [ master, main, tests ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: [ '8.2', '8.3', '8.4' ]

    name: PHP ${{ matrix.php-version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mysqli
          coverage: none        # switch to 'xdebug' when you want coverage reports

      - name: Cache Composer packages
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ matrix.php-version }}-${{ hashFiles('composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-${{ matrix.php-version }}-

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Run Unit tests
        run: vendor/bin/phpunit --testsuite Unit --colors=always
